# Generated by Django 3.0.3 on 2020-09-12 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
